console.log("Wlecome to GIT")
console.log("Welcome to GITHUB")
console.log("Welcome to JENKINS")
console.log("Welcome to CI/CD PIPELINE")
console.log("Welcome to ONLINE AUTOMATION")
console.log("Welcome to PLAYWRIGHT SESSIONS")