console.log("Git Practice Sessions")
console.log("GitHub Practice Sessions")
console.log("Playwright Practice Sessions")
console.log("Typescript Practice Sessions")
console.log("JavaScript Practice Sessions")
